name = "Interpolation"
uuid = "2eb8bd3d-4ed5-451c-82ee-dcf55ee37273"
authors = ["Will M. Farr <wfarr-vscholar@flatironinstitute.org>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
